# Generated by Django 5.2 on 2025-04-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="committee",
        ),
    ]
