# Generated by Django 5.2 on 2025-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
