# Generated by Django 5.2 on 2025-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_post_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='post',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
