# Generated by Django 5.2 on 2025-05-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_alter_post_attachement_alter_post_poster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="attachement",
            new_name="attachment",
        ),
    ]
