# Generated by Django 5.2 on 2025-04-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='author',
            new_name='committee',
        ),
    ]
