# Generated by Django 5.2 on 2025-04-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_rename_author_activity_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="slug",
            field=models.SlugField(default="abc", max_length=200),
            preserve_default=False,
        ),
    ]
