# Generated by Django 5.2 on 2025-04-29 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_alter_activity_slug"),
        ("committees", "0004_alter_committee_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="committees.committee",
            ),
        ),
    ]
