# Generated by Django 5.2 on 2025-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
