# Generated by Django 5.2.5 on 2025-08-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0005_alter_committee_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="contact_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contact person",
            ),
        ),
    ]
