# Generated by Django 5.2.5 on 2025-08-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
